#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
JAVA_HOME="$(cd "$DIR" && pwd)"
echo -e "export JAVA_HOME=${JAVA_HOME}">>/etc/profile
echo -e 'export CLASSPATH=.:${JAVA_HOME}/lib\nexport PATH=$PATH:${JAVA_HOME}/bin'>>/etc/profile
source /etc/profile
